/// Flutter icons CustomFlagIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomFlagIcon
///      fonts:
///       - asset: fonts/CustomFlagIcon.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class CustomFlagIcon {
  CustomFlagIcon._();

  static const _kFontFam = 'CustomFlagIcon';

  static const IconData flag = const IconData(0xe800, fontFamily: _kFontFam);
}
