/// Flutter icons NotesIndicator
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NotesIndicator
///      fonts:
///       - asset: fonts/NotesIndicator.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
///
import 'package:flutter/widgets.dart';

class NotesIndicator {
  NotesIndicator._();

  static const _kFontFam = 'NotesIndicator';

  static const IconData doc_text = const IconData(0xe800, fontFamily: _kFontFam);
}
