/// Flutter icons EditScreenCalendar
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EditScreenCalendar
///      fonts:
///       - asset: fonts/EditScreenCalendar.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
///
import 'package:flutter/widgets.dart';

class EditScreenCalendar {
  EditScreenCalendar._();

  static const _kFontFam = 'EditScreenCalendar';

  static const IconData calendar = const IconData(0xe800, fontFamily: _kFontFam);
}
