/// Flutter icons NotificationBells
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NotificationBells
///      fonts:
///       - asset: fonts/NotificationBells.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class NotificationBells {
  NotificationBells._();

  static const _kFontFam = 'NotificationBells';

  static const IconData bell = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData bell_off_empty = const IconData(0xf1f7, fontFamily: _kFontFam);
}
