/// Flutter icons SetTimeIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SetTimeIcon
///      fonts:
///       - asset: fonts/SetTimeIcon.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class SetTimeIcon {
  SetTimeIcon._();

  static const _kFontFam = 'SetTimeIcon';

  static const IconData clock = const IconData(0xe800, fontFamily: _kFontFam);
}
