/// Flutter icons TaskDate
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TaskDate
///      fonts:
///       - asset: fonts/TaskDate.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
///
import 'package:flutter/widgets.dart';

class TaskDate {
  TaskDate._();

  static const _kFontFam = 'TaskDate';

  static const IconData calendar = const IconData(0xe801, fontFamily: _kFontFam);
}
